### ISSUE TITLE
Fix payment page

### ISSUE THREAD

**Issue by expeon07** [widifadi/eVivlio#50]
- [x] Extra space on the right
- [ ] Cancel button as red or grey
- [x] Center the buttons
- [ ] Change "please proceed to payment" since user is already on payment page?

![image](https://user-images.githubusercontent.com/55695281/120715189-2a72e280-c4bc-11eb-92a7-9563ee9b9864.png)

**Comment by EngrAAhmed** [comment]
resolved...
