### ISSUE TITLE
Date issue on card details form 

### ISSUE THREAD

**Issue by widifadi** [widifadi/eVivlio#61]
![image](https://user-images.githubusercontent.com/82517622/120841528-48038300-c574-11eb-81a5-5dbd831a4836.png)

Should check if the date enter is valid

**Comment by expeon07** [comment]
I thought it was expiration date of the card, but you insert this date to the order and payment tables, so they're payment date and order date. Therefore delete this from the form and get the date from the server.

**Comment by EngrAAhmed** [comment]
Resolved..
